### ISSUE TITLE
필터링 - 카테고리, 타입, 가격

### ISSUE THREAD

**Issue by sanghee1115** [TEAM3x3/backend#16]
--------------------
**View**
- [x] 카테고리에 따른 분류
- [x] 타입에 따른 분류
- [x] 가격 높은 순
- [x] 가격 낮은 순

--------------------------
**TestCode**
- [x] 카테고리에 따른 분류
- [x] 타입에 따른 분류
- [x] 가격 높은 순
- [x] 가격 낮은 순

**Comment by jeonyh0924** [comment]
샛별지역/ 택배지역은 ios가 상품 명은 백엔드가
